version: '3.9'
services:
  webapp:
    command: uwsgi --ini app.ini
    expose:
      - 5000
    environment:
      - PG_PASSWORD=student_password
      - PG_USER=student_user
      - PG_DATABASE=labo
      - PG_PORT=5432
      - PG_HOST=postgres
  nginx:
    expose:
      - 80
  postgres:
    image: 'postgres:15.1-alpine'
    environment:
      - POSTGRES_PASSWORD=student_password
      - POSTGRES_USER=student_user
      - POSTGRES_DB=labo
